### ISSUE TITLE
circle alpha 방법 코드에서 오타가 있습니다.

### ISSUE THREAD

**Issue by humit0** [kairess/genetic_image#1]
https://github.com/kairess/genetic_image/blob/5d421d2cb60e9aebc6083dc11fda3035dad8f5f9/circle_alpha.py#L51

해당 줄이 75가 아니라 0.75가 되어야 할 것 같습니다.

**Comment by kairess** [comment]
@humit0 아 그러네요 ㅋㅋㅋ ㅠ 감사합니다!

**Comment by humit0** [comment]
반영해주셔서 감사합니다. 영상 잘 보고 있습니다!!
